name: Build & Push Unity Hub

on:
  workflow_dispatch:
    inputs:
      hub_version:
        description: 'Unity Hub version tag (e.g., 3.7.0)'
        required: true
        default: '3.7.0'
      base_tag:
        description: 'Base image tag (e.g., 22.04)'
        required: true
        default: '22.04'

jobs:
  build-hub:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set repository name to lowercase
        id: repo_name
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push hub image
        uses: docker/build-push-action@v5
        with:
          context: ./hub
          file: ./hub/Dockerfile
          build-args: |
            baseImage=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerized-unity-base:${{ github.event.inputs.base_tag }}
            hubVersion=${{ github.event.inputs.hub_version }}
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerized-unity-hub:${{ github.event.inputs.hub_version }}-ubuntu${{ github.event.inputs.base_tag }}
          push: true
# After this workflow completes, the hub image will be available as docker.io/USERNAME/containerized-unity-hub:HUBVERSION-ubuntuBASETAG
# Make sure the base image exists before running this workflow.