name: Build & Push Unity Editor

on:
  workflow_dispatch:
    inputs:
      base_tag:
        description: 'Base image tag (e.g., 22.04)'
        required: true
        default: '22.04'
      hub_version:
        description: 'Unity Hub version (e.g., 3.7.0)'
        required: true
        default: '3.12.1'
      editor_version:
        description: 'Unity Editor version (e.g., 6000.0.48f1)'
        required: true
        default: '6000.0.48f1'
      editor_changeset:
        description: 'Unity Editor changeset (e.g., 170d2541580d)'
        required: true
        default: '170d2541580d'
      editor_modules:
        description: 'Unity Editor modules (space separated, e.g., android webgl)'
        required: true
        default: 'android webgl ios'
      architecture:
        description: 'Target architecture (x86_64, arm64, or both)'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - x86_64
          - arm64
          - both
      runner:
        description: 'Runner type (mkt or self-hosted)'
        required: true
        default: 'mkt'
        type: choice
        options:
          - mkt
          - self-hosted

jobs:
  build-editor:
    runs-on: ${{ github.event.inputs.runner || 'mkt' }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Show Buildx version
        run: docker buildx version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set platform based on input
        id: platform
        run: |
          if ($env:GITHUB_EVENT_INPUTS_ARCHITECTURE -eq "both") {
            "platforms=linux/amd64,linux/arm64" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } elseif ($env:GITHUB_EVENT_INPUTS_ARCHITECTURE -eq "arm64") {
            "platforms=linux/arm64" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            "platforms=linux/amd64" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }
        shell: pwsh

      - name: Build and push editor image
        uses: docker/build-push-action@v5
        with:
          context: ./editor
          file: ./editor/Dockerfile
          platforms: ${{ steps.platform.outputs.platforms }}
          build-args: |
            baseImage=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerized-unity-base:${{ github.event.inputs.base_tag }}
            hubImage=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerized-unity-hub:${{ github.event.inputs.hub_version }}-ubuntu${{ github.event.inputs.base_tag }}-${{ github.event.inputs.architecture }}
            version=${{ github.event.inputs.editor_version }}
            changeSet=${{ github.event.inputs.editor_changeset }}
            module=${{ github.event.inputs.editor_modules }}
            architecture=${{ github.event.inputs.architecture }}
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerized-unity-editor:${{ github.event.inputs.editor_version }}-${{ github.event.inputs.architecture }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prune Docker (self-hosted only)
        if: runner.os != 'Linux' # Remove or adjust this line if you want to prune on all runners
        run: docker system prune -af

      - name: Notify Discord
        if: always()
        run: |
          $body = @{
            content = "Build $env:GITHUB_JOB_STATUS for Unity Editor Docker image`n- **Image:** docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerized-unity-editor:${{ github.event.inputs.editor_version }}-${{ github.event.inputs.architecture }}`n- **Base Tag:** ${{ github.event.inputs.base_tag }}`n- **Hub Version:** ${{ github.event.inputs.hub_version }}`n- **Unity Version:** ${{ github.event.inputs.editor_version }}`n- **Architecture:** ${{ github.event.inputs.architecture }}`n- **Editor Modules:** ${{ github.event.inputs.editor_modules }}"
          } | ConvertTo-Json
          Invoke-RestMethod -Uri "${{ secrets.DISCORD_WEBHOOK }}" -Method Post -ContentType 'application/json' -Body $body
        shell: pwsh