name: Build & Push Unity Hub

on:
  workflow_dispatch:
    inputs:
      hub_version:
        description: 'Unity Hub version tag (e.g., 3.7.0)'
        required: true
        default: '3.12.1'
      base_tag:
        description: 'Base image tag (e.g., 22.04)'
        required: true
        default: '22.04'
      architecture:
        description: 'Target architecture (x86_64, arm64, or both)'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - x86_64
          - arm64
          - both

jobs:
  build-hub:
    runs-on: mkt
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set repository name to lowercase
        id: repo_name
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set platform based on input
        id: platform
        run: |
          if [[ "${{ github.event.inputs.architecture }}" == "both" ]]; then
            echo "platforms=linux/amd64,linux/arm64" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.architecture }}" == "arm64" ]]; then
            echo "platforms=linux/arm64" >> $GITHUB_OUTPUT
          else
            echo "platforms=linux/amd64" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Build and push hub image
        uses: docker/build-push-action@v5
        with:
          context: ./hub
          file: ./hub/Dockerfile
          platforms: ${{ steps.platform.outputs.platforms }}
          build-args: |
            baseImage=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerized-unity-base:${{ github.event.inputs.base_tag }}
            hubVersion=${{ github.event.inputs.hub_version }}
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerized-unity-hub:${{ github.event.inputs.hub_version }}-ubuntu${{ github.event.inputs.base_tag }}-${{ github.event.inputs.architecture }}
          push: true
# After this workflow completes, the hub image will be available as docker.io/USERNAME/containerized-unity-hub:HUBVERSION-ubuntuBASETAG-ARCHITECTURE
# Make sure the base image exists before running this workflow.
