name: Build & Push Unity Base

on:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: 'Ubuntu version (e.g., 22.04)'
        required: true
        default: '22.04'

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./base
          file: ./base/Dockerfile
          # If you want to support multiple Ubuntu versions, you can add an ARG in your Dockerfile and pass it here
          tags: |
            ghcr.io/${{ github.repository }}/unity-base:${{ github.event.inputs.ubuntu_version }}
          push: true
# After this workflow completes, the base image will be available as ghcr.io/OWNER/REPO/unity-base:22.04 (or your chosen version)