name: Build & Push Unity Hub

on:
  workflow_dispatch:
    inputs:
      hub_version:
        description: 'Unity Hub version tag (e.g., 3.7.0)'
        required: true
        default: '3.7.0'
      base_tag:
        description: 'Base image tag (e.g., 22.04)'
        required: true
        default: '22.04'

jobs:
  build-hub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push hub image
        uses: docker/build-push-action@v5
        with:
          context: ./hub
          file: ./hub/Dockerfile
          build-args: |
            baseImage=ghcr.io/${{ github.repository }}/unity-base:${{ github.event.inputs.base_tag }}
            hubVersion=${{ github.event.inputs.hub_version }}
          tags: |
            ghcr.io/${{ github.repository }}/unity-hub:${{ github.event.inputs.hub_version }}-ubuntu${{ github.event.inputs.base_tag }}
          push: true
# After this workflow completes, the hub image will be available as ghcr.io/OWNER/REPO/unity-hub:HUBVERSION-ubuntuBASETAG
# Make sure the base image exists before running this workflow.