name: Build & Push Bundletool Image

on:
  workflow_dispatch:

jobs:
  build-bundletool:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push bundletool image
        uses: docker/build-push-action@v5
        with:
          context: ./bundletool
          file: ./bundletool/Dockerfile
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/bundletool:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
